version: "3.8"
services:
    drupal_db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: drupal
            # So you don't have to use root, but you can if you like
            MYSQL_USER: user
            # You can use whatever password you like
            MYSQL_PASSWORD: password
            # Password for root access
            MYSQL_ROOT_PASSWORD: password
        expose: 
            - '3306'

    drupal:
        build: .
        restart: always
        volumes:
            - ./modules:/opt/drupal/web/modules/custom
            - ./scripts/install.sh:/opt/drupal/install.sh
        ports: 
            - 80:80


